### ISSUE TITLE
RuntimeError: memory access out of bounds on CoalesceImages

### ISSUE THREAD

**Issue by geocine** [dlemstra/magick-wasm#173]
### magick-wasm version

0.0.30

### Description

Running coalesce inside readCollection on a GIF causes the native module to throw an memory access out of bounds exception
```sh
VM2835:1 Error processing GIF: RuntimeError: memory access out of bounds
    at magick.dfc94ac5f18be68f99c9.wasm:0x8f67
    at magick.dfc94ac5f18be68f99c9.wasm:0x2809f3
    at magick.dfc94ac5f18be68f99c9.wasm:0x80938
    at magick.dfc94ac5f18be68f99c9.wasm:0x151a9d
    at magick.dfc94ac5f18be68f99c9.wasm:0x384918
    at magick.dfc94ac5f18be68f99c9.wasm:0x8e91f3
    at e._MagickImageCollection_Coalesce (magick.js:8:1)
    at magick-image-collection.ts:439:1
    at magick-image-collection.ts:811:1
    at exception.ts:39:1
    at Ge.use (int-pointer.ts:18:1)
    at T.use (exception.ts:38:1)
    at magick-image-collection.ts:809:1
    at Me.attachImages (magick-image-collection.ts:729:1)
    at Me.replaceImages (magick-image-collection.ts:809:1)
    at Me.coalesce (magick-image-collection.ts:439:1)
   ```

### Steps to Reproduce

```js
ImageMagick.readCollection(data, MagickFormat.Gif, (images) => {
      images.coalesce(); // throws the exception here
});
```

### Images

https://drive.google.com/file/d/1jeToienatAO07jRmZYpLMlK0MJgBFUcx/view?usp=sharing 

This is a zipped file with the GIF image used. 
```
Format                                   : GIF
Format/Info                              : Graphics Interchange Format
File size                                : 90.7 MiB

Image
Format                                   : GIF
Format/Info                              : Graphics Interchange Format
Format profile                           : 89a
Width                                    : 1 331 pixels
Height                                   : 1 331 pixels
Compression mode                         : Lossless
```
The GIF has 201 frames as read by `ImageMagick.readCollection`

**Comment by dlemstra** [comment]
I suspect that you are running out of memory because wasm only runs in 32-bit and has a memory limit. But I will need some time to investigate this.

**Comment by ajitjadhav28** [comment]
my be you are right ! I tried to run `/usr/bin/time -v convert Big\ Animation.gif -coalesce off%d.png` on provided image. It consumed almost 3GB of RAM. Check the attached screenshot below.

![image](https://github.com/user-attachments/assets/cdf7dcfb-3217-4e97-9cf4-04451e301c49)
