### ISSUE TITLE
Build Error with BigInt Literals and 'use client' in Vite

### ISSUE THREAD

**Issue by idebenone** [dlemstra/magick-wasm#188]
### magick-wasm version

0.0.31

### Description

I am trying to build a [Wails](https://wails.io/) app using Vite with React.
I am experiencing build errors.

```
PS D:\convert> wails dev
Wails CLI v2.9.2

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:     
    > frontend@0.0.0 build
    > tsc && vite build
    
    vite v3.2.11 building for production...
    transforming...
    ✓ 1669 modules transformed.
    
    [vite:esbuild-transpile] Transform failed with 5 errors:
    assets/index.27a7d11f.js:19929:17: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    assets/index.27a7d11f.js:19929:23: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    assets/index.27a7d11f.js:19929:30: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    assets/index.27a7d11f.js:22509:24: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    assets/index.27a7d11f.js:22518:24: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    
    Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    19927|        a = ee(a);
    19928|        var c = it(i), m = a.indexOf("u") != -1;
    19929|        m && (u = (1n << 64n) - 1n), me(n, { name: a, fromWireType: function(f) {
       |                   ^
    19930|          return f;
    19931|        }, toWireType: function(f, h) {

    Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    19927|        a = ee(a);
    19928|        var c = it(i), m = a.indexOf("u") != -1;
    19929|        m && (u = (1n << 64n) - 1n), me(n, { name: a, fromWireType: function(f) {
       |                         ^
    19930|          return f;
    19931|        }, toWireType: function(f, h) {

    Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    19927|        a = ee(a);
    19928|        var c = it(i), m = a.indexOf("u") != -1;
    19929|        m && (u = (1n << 64n) - 1n), me(n, { name: a, fromWireType: function(f) {
       |                                ^
    19930|          return f;
    19931|        }, toWireType: function(f, h) {

    Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    22507|        } catch (c) {
    22508|          if (F(u), c !== c + 0) throw c;
    22509|          return H(1, 0), 0n;
       |                          ^
    22510|        }
    22511|      }

    Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    22516|        } catch (s) {
    22517|          if (F(i), s !== s + 0) throw s;
    22518|          return H(1, 0), 0n;
       |                          ^
    22519|        }
    22520|      }

    error during build:
    Error: Transform failed with 5 errors:
    assets/index.27a7d11f.js:19929:17: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    assets/index.27a7d11f.js:19929:23: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    assets/index.27a7d11f.js:19929:30: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    assets/index.27a7d11f.js:22509:24: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
    assets/index.27a7d11f.js:22518:24: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
        at failureErrorWithLog (D:\convert\frontend\node_modules\esbuild\lib\main.js:1575:15)
        at D:\convert\frontend\node_modules\esbuild\lib\main.js:814:29
        at responseCallbacks.<computed> (D:\convert\frontend\node_modules\esbuild\lib\main.js:680:9)
        at handleIncomingPacket (D:\convert\frontend\node_modules\esbuild\lib\main.js:735:9)
        at Socket.readFromStdout (D:\convert\frontend\node_modules\esbuild\lib\main.js:656:7)
        at Socket.emit (node:events:519:28)
        at addChunk (node:internal/streams/readable:559:12)
        at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
        at Readable.push (node:internal/streams/readable:390:5)
        at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)


  ERROR   exit status 1
  ```

### Steps to Reproduce

- clone this [repo](https://github.com/idebenone/convert)
- navigate to the root and execute `wails dev`

**Comment by dlemstra** [comment]
This is not a project issue? But more an issue with your build configuration? You will need to tweak some settings in your project to allow support for bigints.
